version: "3.8"

services:
  backend:
    build:
      context: ../../backend
    restart: always
    volumes:
      - ../../backend:/usr/src/
    ports:
      - 8000:8000

  frontend:
    build:
      context: ../../frontend
    restart: always
    volumes:
      - ../../frontend:/usr/src/
    ports:
      - 3000:3000
